name: Move issue to Backlog when label added

on:
  issues:
    types:
      - labeled

jobs:
  move_to_backlog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move issue to Backlog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: "PVT_kwHOB16rWM4ApMGw" # Set your GitHub project ID here
          BACKLOG_COLUMN_ID: "394f8d2b" # Set the column ID for 'Backlog' here
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_NODE_ID=$(curl -H "Authorization: bearer $GITHUB_TOKEN" \
                              -X POST \
                              -H "Content-Type: application/json" \
                              -d '{"query":"query { repository(owner: \\"'${{ github.repository_owner }}'\\", name: \\"'${{ github.event.repository.name }}'\\") { issue(number: '$ISSUE_NUMBER') { id } } }"}' \
                              https://api.github.com/graphql | jq -r .data.repository.issue.id)
          
          # Gebe die Issue-Node-ID in der Konsole aus
          echo "The Issue Number is: $ISSUE_NUMBER"
          echo "The Issue Node ID is: $ISSUE_NODE_ID"
          
          
          LABEL_NAME=${{ github.event.label.name }}
          
          # Prüfen, ob das Label korrekt ist
          if [ "$LABEL_NAME" == "feature" ]; then
            echo "update field $ISSUE_NUMBER"
          else
            echo "Label does not match the trigger label."
          fi
