name: Move Issue to Backlog on Label

on:
  issues:
    types: [labeled]

jobs:
  move_to_backlog:
    if: contains(github.event.label.name, 'feature')
    runs-on: ubuntu-latest

    steps:
      - name: Move issue to Backlog column
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.inertia-preview+json" \
          https://api.github.com/projects/columns/394f8d2b/cards \
          -d '{"content_id": "${{ github.event.issue.id }}", "content_type": "Issue"}'
