name: Set project status to Backlog on feature label

on:
  issues:
    types:
      - labeled

permissions:
  contents: read
  issues: write

jobs:
  move_to_backlog:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Backlog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          project_column_id="394f8d2b"

          # Move the issue to the "Backlog" column
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /projects/columns/$project_column_id/cards \
            -F "content_id=${{ github.event.issue.id }}" \
            -F "content_type=Issue"
