name: Set project status to Backlog on feature label

on:
  issues:
    types:
      - labeled

permissions:
  contents: read
  issues: write

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Test-Project
          column: Backlog
          repo-token: ${{ secrets.PAT_TOKEN }}

