name: Set project status to Backlog on feature label

on:
  issues:
    types:
      - labeled

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Test-Project
          column: Backlog
          repo-token: ${{ secrets.PAT_TOKEN }}

