name: Update Status on Feature Label

on:
  issues:
    types:
      - labeled

jobs:
  update_status:
    if: github.event.label.name == 'feature'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set issue status to "Backlog"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          FIELD_ID: 'PVTSSF_lAHOB16rWM4ApMGwzggoz7Y'  # Hier die ID des Custom Fields eintragen
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER} \
            -d '{"custom_field": { "id": "'$FIELD_ID'", "value": "Backlog" }}'
