name: Add Issue to Project Backlog

on:
  issues:
    types: [labeled]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Project Backlog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"query":"mutation { addProjectNextItem(input: {projectId: \"10797488\", contentId: \"${{ github.event.issue.node_id }}\"}) { projectNextItem { id } } }"}' \
          https://api.github.com/graphql
