name: Print All Status Options

on:
  workflow_dispatch:  # Manuell startbarer Workflow

jobs:
  print-status-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Status Options
        run: |
          # Führe eine GraphQL-Abfrage aus, um die Status-Optionen zu holen
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "query { user(login: \"yoo-gop\") { projectV2(number: 1) { fields(first: 20) { 
          nodes { ... on ProjectV2SingleSelectField { name options { id name } } } } } } }"}' \
            https://api.github.com/graphql)

          # Überprüfen, ob die API-Antwort erfolgreich ist
          if echo "$RESPONSE" | grep -q '"data":'; then
            echo "Status Options (Label und ID):"
            echo "$RESPONSE" | jq -r '.data.user.projectV2.fields.nodes[] | select(.name == "Status") | .options[] | "Label: \(.name), ID: \(.id)"'
          else
            echo "Fehler: Ungültige API-Antwort."
            echo "$RESPONSE"
          fi
