name: Print Issue on Label Added

on:
  issues:
    types:
      - labeled

jobs:
  print-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print issue details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Added Label: ${{ github.event.label.name }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
