name: Test Personal Access Token and Project Access

on:
  workflow_dispatch:  # Ermöglicht das manuelle Ausführen des Workflows

jobs:
  test-pat-access:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Schritt 2: Teste den Zugriff auf die GitHub API mit dem PAT
      - name: Test PAT Access to GitHub API
        run: |
          # Teste Zugriff mit einer einfachen GraphQL-Anfrage (Viewer Login)
          RESPONSE=$(curl -H "Authorization: bearer ${{ secrets.PAT_TOKEN }}" \
                -X POST \
                -H "Content-Type: application/json" \
                -d '{"query": "query { viewer { login }}"}' \
                https://api.github.com/graphql)

          # Ausgabe der API-Antwort
          echo "GraphQL API Response: $RESPONSE"

          # Überprüfen, ob der Login erfolgreich abgerufen wurde
          LOGIN=$(echo "$RESPONSE" | jq -r .data.viewer.login)
          if [ "$LOGIN" != "null" ]; then
            echo "Success! PAT has access to GitHub API. Viewer login: $LOGIN"
          else
            echo "Error: Unable to access GitHub API with the provided PAT."
            exit 1
          fi

      # Schritt 3: Teste den Zugriff auf das GitHub Project V2 eines Benutzers
      - name: Test PAT Access to GitHub Project V2
        run: |
          # Füge die Project Number und den Benutzernamen ein
          PROJECT_NUMBER="1"  # Ersetze dies durch deine Projekt-Nummer
          USER_NAME="YOUR_USER_NAME"  # Ersetze dies durch deinen GitHub-Benutzernamen

          # Teste Zugriff auf das spezifische GitHub Project V2
          RESPONSE=$(curl -H "Authorization: bearer ${{ secrets.PAT_TOKEN }}" \
                -X POST \
                -H "Content-Type: application/json" \
                -d "{\"query\": \"query { user(login: \\\"$USER_NAME\\\") { projectV2(number: $PROJECT_NUMBER) { title } } }\"}" \
                https://api.github.com/graphql)

          # Ausgabe der API-Antwort
          echo "GraphQL API Response: $RESPONSE"

          # Überprüfen, ob der Projektname erfolgreich abgerufen wurde
          PROJECT_TITLE=$(echo "$RESPONSE" | jq -r .data.user.projectV2.title)
          if [ "$PROJECT_TITLE" != "null" ]; then
            echo "Success! PAT has access to GitHub Project V2. Project title: $PROJECT_TITLE"
          else
            echo "Error: Unable to access the specified GitHub Project V2 with the provided PAT."
            exit 1
          fi

            echo "Error: Unable to access the specified GitHub Project V2 with the provided PAT."
            exit 1
          fi
