name: Test Personal Access Token and Project Access

on:
  workflow_dispatch:  # Ermöglicht das manuelle Ausführen des Workflows

jobs:
  test-pat-access:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # Schritt 2: Teste den Zugriff auf die GitHub API mit dem PAT
      - name: Test PAT Access to GitHub API
        run: |
          # Teste Zugriff mit einer einfachen GraphQL-Anfrage (Viewer Login)
          RESPONSE=$(curl -H "Authorization: bearer ${{ secrets.PAT_TOKEN }}" \
                -X POST \
                -H "Content-Type: application/json" \
                -d '{"query": "query { viewer { login }}"}' \
                https://api.github.com/graphql)

          # Ausgabe der API-Antwort
          echo "GraphQL API Response: $RESPONSE"

          # Überprüfen, ob der Login erfolgreich abgerufen wurde
          LOGIN=$(echo "$RESPONSE" | jq -r .data.viewer.login)
          if [ "$LOGIN" != "null" ]; then
            echo "Success! PAT has access to GitHub API. Viewer login: $LOGIN"
          else
            echo "Error: Unable to access GitHub API with the provided PAT."
            exit 1
          fi

      # Schritt 3: Teste den Zugriff auf das GitHub Project V2
      - name: Test PAT Access to GitHub Project V2
        run: |
          # Füge die Project ID ein
          PROJECT_ID="PVT_kwHOB16rWM4ApMGw"

          # Teste Zugriff auf das spezifische GitHub Project V2
          RESPONSE=$(curl -H "Authorization: bearer ${{ secrets.PAT_TOKEN }}" \
                -X POST \
                -H "Content-Type: application/json" \
                -d "{\"query\": \"query { projectV2(id: \\\"$PROJECT_ID\\\") { title } }\"}" \
                https://api.github.com/graphql)

          # Ausgabe der API-Antwort
          echo "GraphQL API Response: $RE
